#!/usr/bin/env python3
"""
SVG-Based Pyramid Position Calculator
Pre-calculates which pyramid positions fit inside the SVG boundary
Generates OpenSCAD code with ONLY valid positions
"""

import numpy as np
from shapely.geometry import Point, Polygon
from shapely.ops import unary_union
from svg.path import parse_path
import xml.etree.ElementTree as ET
from pathlib import Path

def parse_svg_to_polygon(svg_file, target_width=100):
    """
    Parse SVG file and convert to Shapely polygon
    Returns polygon scaled to target_width
    """
    tree = ET.parse(svg_file)
    root = tree.getroot()
    
    # Extract paths from SVG
    # This is simplified - real implementation would need to handle
    # multiple paths, transforms, etc.
    paths = []
    for path_elem in root.findall('.//{http://www.w3.org/2000/svg}path'):
        d = path_elem.get('d')
        if d:
            path = parse_path(d)
            paths.append(path)
    
    # Convert paths to point lists
    # (Simplified - would need proper curve sampling)
    points = []
    for path in paths:
        for segment in path:
            points.append((segment.start.real, segment.start.imag))
    
    # Create polygon
    if len(points) > 2:
        poly = Polygon(points)
        
        # Scale to target width
        bounds = poly.bounds
        current_width = bounds[2] - bounds[0]
        scale_factor = target_width / current_width
        
        # Scale and return
        from shapely.affinity import scale as shapely_scale
        poly_scaled = shapely_scale(poly, xfact=scale_factor, yfact=scale_factor, origin=(0, 0))
        return poly_scaled
    
    return None

def calculate_valid_pyramid_positions(
    polygon,
    pyramid_size=4,
    pyramid_spacing=1,
    target_width=100
):
    """
    Calculate which pyramid positions fit completely inside the polygon
    Returns list of [x, y] positions
    """
    pyramid_pitch = pyramid_size + pyramid_spacing
    pyramid_radius = pyramid_size * 0.707  # Rotated square diagonal
    hex_vertical_spacing = pyramid_pitch * 0.866
    
    valid_positions = []
    
    # Calculate number of rows
    num_rows = int(np.ceil(target_width / hex_vertical_spacing))
    
    for row in range(num_rows + 1):
        # Offset every other row for hex pattern
        x_offset = (row % 2) * (pyramid_pitch / 2)
        
        num_cols = int(np.ceil(target_width / pyramid_pitch))
        for col in range(num_cols + 1):
            x_pos = col * pyramid_pitch + x_offset
            y_pos = row * hex_vertical_spacing
            
            # Create a circle representing the pyramid footprint
            pyramid_footprint = Point(x_pos, y_pos).buffer(pyramid_radius)
            
            # Check if pyramid footprint is COMPLETELY inside the polygon
            if polygon.contains(pyramid_footprint):
                valid_positions.append([x_pos, y_pos])
    
    return valid_positions

def generate_openscad_with_positions(
    svg_file,
    valid_positions,
    output_file,
    **params
):
    """
    Generate OpenSCAD file with pre-calculated valid pyramid positions
    """
    
    scad_code = f"""// AUTO-GENERATED by pyramid position calculator
// Valid pyramid positions pre-calculated from SVG boundary

// ===== PARAMETERS =====
svg_file = "{svg_file}";
target_width = {params.get('target_width', 100)};
maintain_aspect_ratio = true;

base_thickness = {params.get('base_thickness', 2)};
outline_offset = {params.get('outline_offset', 2)};
outline_height = {params.get('outline_height', 0.8)};

pyramid_size = {params.get('pyramid_size', 4)};
pyramid_height = {params.get('pyramid_height', 2.5)};
pyramid_style = {params.get('pyramid_style', 4)};

total_height = base_thickness + outline_height;

// ===== PRE-CALCULATED VALID POSITIONS =====
// These positions have been verified to fit completely inside the SVG boundary
valid_pyramid_positions = [
"""
    
    # Add all valid positions
    for pos in valid_positions:
        scad_code += f"    [{pos[0]:.3f}, {pos[1]:.3f}],\n"
    
    scad_code += """];

// ===== MODULES =====

module scaled_svg() {
    resize([target_width, 0, 0], auto=maintain_aspect_ratio) {
        import(svg_file);
    }
}

module base_shape_2d() {
    scaled_svg();
}

module outlined_shape_2d() {
    offset(r = outline_offset) {
        base_shape_2d();
    }
}

module grip_pyramid() {
    rotate([0, 0, 45]) {
        cylinder(
            h = pyramid_height,
            r1 = pyramid_size / 1.414,
            r2 = 0,
            $fn = pyramid_style
        );
    }
}

// Place pyramids at pre-calculated positions
module pyramids_on_surface() {
    for (pos = valid_pyramid_positions) {
        translate([pos[0], pos[1], total_height]) {
            grip_pyramid();
        }
    }
}

// ===== ASSEMBLY =====

module stomp_pad_complete() {
    union() {
        // Base layer
        linear_extrude(height = base_thickness) {
            base_shape_2d();
        }
        
        // Raised outline border
        difference() {
            linear_extrude(height = total_height) {
                outlined_shape_2d();
            }
            translate([0, 0, base_thickness]) {
                linear_extrude(height = total_height) {
                    base_shape_2d();
                }
            }
        }
        
        // Pyramids at valid positions only
        pyramids_on_surface();
    }
}

stomp_pad_complete();
"""
    
    with open(output_file, 'w') as f:
        f.write(scad_code)
    
    print(f"Generated {output_file}")
    print(f"Valid pyramid positions: {len(valid_positions)}")

def main():
    """
    Example usage
    """
    svg_file = "test_logo.svg"
    
    # Parse SVG to polygon
    print(f"Parsing {svg_file}...")
    polygon = parse_svg_to_polygon(svg_file, target_width=100)
    
    if polygon is None:
        print("ERROR: Could not parse SVG to polygon")
        return
    
    # Calculate valid positions
    print("Calculating valid pyramid positions...")
    valid_positions = calculate_valid_pyramid_positions(
        polygon,
        pyramid_size=4,
        pyramid_spacing=1,
        target_width=100
    )
    
    # Generate OpenSCAD file
    output_file = "stomp_pad_precalculated.scad"
    generate_openscad_with_positions(
        svg_file,
        valid_positions,
        output_file,
        target_width=100,
        base_thickness=2,
        outline_offset=2,
        outline_height=0.8,
        pyramid_size=4,
        pyramid_height=2.5,
        pyramid_style=4
    )
    
    print(f"\n✓ Done! Open {output_file} in OpenSCAD")

if __name__ == "__main__":
    main()
