#!/usr/bin/env python3
"""Stomp-pad geometry pipeline.

Phase 0 packaged the previous monolithic ``pyramid_position_calculator.py``
into ``stomppad/``. Phase 1.1 split SVG parsing into
:mod:`stomppad.geometry` (component-aware, with holes and background
auto-drop) and added :mod:`stomppad.project` (the ``ShapeProject`` model
that's the cross-frontend contract). Skeleton + packing + OpenSCAD
generation still live here and move out in Phase 1.2 / Phase 3.
"""

import numpy as np
from shapely.ops import unary_union

from .geometry import (
    Component,
    parse_svg_to_components,
)
from .packing import (
    PackContext,
    calculate_centerline_tangent,
    calculate_skeleton,
    calculate_valid_pyramid_positions,
    create_pyramid_footprint,
    pack_component,
)
from .project import (
    Body,
    DEFAULT_PATTERN,
    EVENT_BODY_CHANGED,
    EVENT_GLOBAL_PARAMS_CHANGED,
    EVENT_SELECTION_CHANGED,
    EVENT_TOPOLOGY_CHANGED,
    SCHEMA_VERSION,
    SIDECAR_SUFFIX,
    ShapeProject,
)
from .cache import BodyOutputCache
# Side-effect import: registers the built-in pattern strategies.
from . import patterns  # noqa: F401


__all__ = [
    # Phase 0 public API — preserved for desktop GUI and web main.js callers.
    "parse_svg_to_polygon",
    "calculate_skeleton",
    "calculate_centerline_tangent",
    "create_pyramid_footprint",
    "calculate_valid_pyramid_positions",
    "generate_openscad_with_positions",
    "save_debug_visualization",
    "main",
    # Phase 1.1 + 1.4 additions.
    "parse_svg_to_components",
    "Component",
    "Body",
    "ShapeProject",
    "SCHEMA_VERSION",
    "DEFAULT_PATTERN",
    # Phase 1.2 + 1.3 additions.
    "pack_component",
    "PackContext",
    "patterns",
    # Phase 2.1 additions.
    "BodyOutputCache",
    "EVENT_BODY_CHANGED",
    "EVENT_GLOBAL_PARAMS_CHANGED",
    "EVENT_SELECTION_CHANGED",
    "EVENT_TOPOLOGY_CHANGED",
    "SIDECAR_SUFFIX",
]


def _log(logger, message):
    """Emit a message via the supplied logger callback, falling back to print."""
    (logger or print)(message)


def parse_svg_to_polygon(svg_file, target_width=100, target_height=None, samples_per_segment=20, logger=None):
    """Back-compat shim over :func:`stomppad.geometry.parse_svg_to_components`.

    Returns ``(polygon, svg_info)`` where ``polygon`` is the union of all
    surviving components (after background auto-drop). Phase 0 callers
    (desktop GUI, web main.js) get the same tuple shape they had before;
    only the **content** changes — multi-path SVGs that used to collapse
    to one weird polygon now union correctly. Single-path SVGs (the
    regression fixture) still produce byte-identical scad output.
    """
    result = parse_svg_to_components(
        svg_file,
        target_width=target_width,
        target_height=target_height,
        samples_per_segment=samples_per_segment,
        logger=logger,
    )
    if result is None:
        return None
    components, svg_info = result
    if not components:
        return None
    # Single-component fast-path: skip unary_union so the regression-fixture
    # output stays bit-identical to Phase 0 (unary_union may normalize ring
    # orientation, which would change downstream coord formatting).
    if len(components) == 1 and not components[0].holes:
        poly = components[0].to_polygon()
    else:
        poly = unary_union([c.to_polygon() for c in components])
    return poly, svg_info


def generate_openscad_with_positions(
        svg_file,
        valid_positions,
        output_file,
        svg_info=None,
        logger=None,
        **params
):
    """
    Generate OpenSCAD file with pre-calculated valid pyramid positions

    Args:
        svg_info: Dictionary with SVG viewBox info (needed for Y-flip)
    """

    # Check if positions include rotation (3 elements vs 2)
    has_rotation = len(valid_positions[0]) == 3 if valid_positions else False

    # Get SVG viewBox height for Y-flip coordinate transformation
    # OpenSCAD imports SVG with Y-axis UP, but Python parses it with Y-axis DOWN
    # We need to flip Y-coordinates to match OpenSCAD's coordinate system
    # Use the SVG viewBox height (scaled) for proper transformation
    viewbox_height = svg_info['viewbox_height'] if svg_info else 0

    scad_code = f"""// AUTO-GENERATED by pyramid position calculator
// Valid pyramid positions pre-calculated from SVG boundary
//
// COORDINATE SYSTEM NOTES:
// - Python parses SVG with Y-axis DOWN (SVG native coordinates)
// - OpenSCAD imports SVG with Y-axis UP (standard 3D coordinates)
// - SVG coordinates are kept in viewBox space (not translated to origin)
// - Y coordinates are flipped: Y_openscad = viewbox_height - Y_python
// - X coordinates remain the same
//
// ROTATION NOTES:
// - Rotation angles calculated from skeleton tangent direction
// - Rotation is relative (tangent direction), so Y-flip doesn't affect it
// - Includes both path-following rotation AND 45° base diamond orientation
// - OpenSCAD applies the rotation directly (already includes diamond rotation)

// ===== PARAMETERS =====
svg_file = "{svg_file}";
// Final dimensions after scaling (calculated by Python)
final_width = {svg_info.get('final_width', params.get('target_width', 100)) if svg_info else params.get('target_width', 100)};
final_height = {svg_info.get('final_height', 0) if svg_info else 0};

base_thickness = {params.get('base_thickness', 2)};
outline_offset = {params.get('outline_offset', 2)};
outline_height = {params.get('outline_height', 0.8)};

pyramid_size = {params.get('pyramid_size', 4)};
pyramid_height = {params.get('pyramid_height', 2.5)};
pyramid_style = {params.get('pyramid_style', 4)};

total_height = base_thickness + outline_height;

// ===== PRE-CALCULATED VALID POSITIONS =====
// These positions have been verified to fit completely inside the SVG boundary
// Format: {"[x, y, rotation]" if has_rotation else "[x, y]"}
// Y-coordinates are flipped to match OpenSCAD's coordinate system
// rotation = angle in degrees for path-following orientation
valid_pyramid_positions = [
"""

    # Add all valid positions with Y-flip for OpenSCAD coordinate system
    for pos in valid_positions:
        x = pos[0]
        y_flipped = viewbox_height - pos[1]  # Flip Y coordinate based on SVG viewBox height
        if has_rotation:
            rotation = pos[2]
            scad_code += f"    [{x:.3f}, {y_flipped:.3f}, {rotation:.3f}],\n"
        else:
            scad_code += f"    [{x:.3f}, {y_flipped:.3f}],\n"

    scad_code += """];

// ===== MODULES =====

module scaled_svg() {
    // Note: OpenSCAD import() automatically handles SVG coordinate system
    // The imported SVG will match the OpenSCAD coordinate system
    // Use resize with both dimensions if height is specified, otherwise auto-scale
    resize([final_width, final_height > 0 ? final_height : 0, 0], auto=true) {
        import(svg_file);
    }
}

module base_shape_2d() {
    scaled_svg();
}

module outlined_shape_2d() {
    offset(r = outline_offset) {
        base_shape_2d();
    }
}

module grip_pyramid(path_rotation=0) {
    // Match the Python footprint calculation: 45° base + path_rotation
    // This ensures OpenSCAD pyramids match the debug visualization
    rotate([0, 0, 45 + path_rotation]) {
        cylinder(
            h = pyramid_height,
            r1 = pyramid_size / 1.414,
            r2 = 0,
            $fn = pyramid_style
        );
    }
}

// Place pyramids at pre-calculated positions
module pyramids_on_surface() {
    for (pos = valid_pyramid_positions) {
"""

    # Sink pyramids 0.01mm into the base so their flat bottom faces aren't
    # coplanar with the top of the base/outline body. Coplanar shared faces
    # crash openscad-wasm's CGAL kernel
    # (CGAL/Nef_3/SNC_external_structure.h:1144). Visually identical;
    # geometrically a clean intersection instead of a touching boundary.
    if has_rotation:
        scad_code += """        translate([pos[0], pos[1], base_thickness - 0.01]) {
            grip_pyramid(path_rotation=pos[2]);
        }
"""
    else:
        scad_code += """        translate([pos[0], pos[1], base_thickness - 0.01]) {
            grip_pyramid();
        }
"""

    scad_code += """    }
}

// ===== ASSEMBLY =====

module stomp_pad_complete() {
    // Base + raised rim as a single body. The earlier two-block formulation
    // (separate base extrude + outlined difference) had a redundant volume —
    // base_shape is a subset of outlined_shape, and the difference only cuts
    // above z=base_thickness, so the base block was fully contained in the
    // outline block. The shared face crashed openscad-wasm's CGAL kernel
    // (CGAL/Nef_3/SNC_external_structure.h:1144). Native OpenSCAD's manifold
    // backend tolerates it; the wasm build does not.
    union() {
        difference() {
            linear_extrude(height = total_height) {
                outlined_shape_2d();
            }
            translate([0, 0, base_thickness]) {
                linear_extrude(height = total_height) {
                    base_shape_2d();
                }
            }
        }

        pyramids_on_surface();
    }
}

stomp_pad_complete();
"""

    with open(output_file, 'w') as f:
        f.write(scad_code)

    _log(logger, f"Generated {output_file}")
    _log(logger, f"Valid pyramid positions: {len(valid_positions)}")


def _polygon_exterior_rings(geom):
    """Yield exterior coordinate rings for Polygon or MultiPolygon."""
    if geom.geom_type == 'Polygon':
        yield geom.exterior.xy
    elif geom.geom_type == 'MultiPolygon':
        for sub in geom.geoms:
            yield sub.exterior.xy


def save_debug_visualization(polygon, skeleton_points, valid_positions, output_file="debug_viz.svg", logger=None):
    """
    Save a debug SVG showing the polygon boundary, skeleton, and pyramid positions
    """
    try:
        import matplotlib.pyplot as plt
        from matplotlib.patches import Polygon as MplPolygon
        import matplotlib.patches as mpatches

        fig, ax = plt.subplots(figsize=(12, 10))

        # Plot polygon boundary (handles MultiPolygon from SVGs with multiple shapes)
        first = True
        for x, y in _polygon_exterior_rings(polygon):
            ax.plot(x, y, 'b-', linewidth=2,
                    label='Polygon Boundary' if first else None)
            first = False

        # Plot skeleton points
        if skeleton_points:
            skeleton_array = np.array(skeleton_points)
            ax.scatter(skeleton_array[:, 0], skeleton_array[:, 1],
                       c='green', s=1, alpha=0.5, label='Skeleton')

        # Plot pyramid positions
        if valid_positions:
            positions = np.array(valid_positions)
            ax.scatter(positions[:, 0], positions[:, 1],
                       c='red', s=20, marker='x', label='Pyramid Centers')

            # Draw pyramid footprints
            for pos in valid_positions:
                if len(pos) == 3:
                    x_pos, y_pos, rotation = pos
                    footprint = create_pyramid_footprint(x_pos, y_pos, 4, rotation)
                    fx, fy = footprint.exterior.xy
                    ax.plot(fx, fy, 'r-', linewidth=0.5, alpha=0.3)

        ax.set_aspect('equal')
        ax.legend()
        ax.grid(True, alpha=0.3)
        ax.set_title('Debug Visualization: Polygon, Skeleton, and Pyramids')

        plt.savefig(output_file, dpi=150, bbox_inches='tight')
        _log(logger, f"  Debug visualization saved: {output_file}")
        plt.close()

    except ImportError:
        _log(logger, "  matplotlib not available for debug visualization")


def main():
    """
    Example usage - configure parameters below
    """
    # ===== CONFIGURATION CONSTANTS =====
    # Input/Output files
    SVG_FILE = "-01.svg"
    OUTPUT_FILE = "stomp_pad_precalculated.scad"
    DEBUG_VIZ_FILE = "debug_viz.png"

    # SVG processing parameters
    TARGET_WIDTH = 152
    TARGET_HEIGHT = None  # Set to a value (e.g., 100) to constrain height, or None for width-only scaling
    SAMPLES_PER_SEGMENT = 40
    SKELETON_RESOLUTION = 0.4

    # Pyramid packing parameters
    PYRAMID_SIZE = 3
    PYRAMID_SPACING = 1.5
    SAFETY_MARGIN = 0.5  # Inset boundary to prevent pyramids from going over edge
    INCLUDE_ROTATION = True

    # OpenSCAD output parameters
    BASE_THICKNESS = 2.5
    OUTLINE_OFFSET = 2
    OUTLINE_HEIGHT = 2
    PYRAMID_HEIGHT = 3.5
    PYRAMID_STYLE = 4  # Number of sides (4 = square pyramid)

    # ===== PROCESSING =====
    # Parse SVG to polygon
    print(f"Parsing {SVG_FILE}...")
    polygon, svg_info = parse_svg_to_polygon(SVG_FILE, target_width=TARGET_WIDTH,
                                             target_height=TARGET_HEIGHT,
                                             samples_per_segment=SAMPLES_PER_SEGMENT)

    if polygon is None:
        print("ERROR: Could not parse SVG to polygon")
        return

    # Calculate skeleton for visualization
    print("Calculating skeleton...")
    skeleton_points = calculate_skeleton(polygon, resolution=SKELETON_RESOLUTION)

    # Calculate valid positions
    print("Calculating valid pyramid positions...")
    valid_positions = calculate_valid_pyramid_positions(
        polygon,
        pyramid_size=PYRAMID_SIZE,
        pyramid_spacing=PYRAMID_SPACING,
        target_width=TARGET_WIDTH,
        include_rotation=INCLUDE_ROTATION,
        safety_margin=SAFETY_MARGIN
    )

    # Save debug visualization
    print("Creating debug visualization...")
    save_debug_visualization(polygon, skeleton_points, valid_positions, DEBUG_VIZ_FILE)

    # Generate OpenSCAD file
    generate_openscad_with_positions(
        SVG_FILE,
        valid_positions,
        OUTPUT_FILE,
        svg_info=svg_info,
        target_width=TARGET_WIDTH,
        base_thickness=BASE_THICKNESS,
        outline_offset=OUTLINE_OFFSET,
        outline_height=OUTLINE_HEIGHT,
        pyramid_size=PYRAMID_SIZE,
        pyramid_height=PYRAMID_HEIGHT,
        pyramid_style=PYRAMID_STYLE
    )

    print(f"\n✓ Done! Open {OUTPUT_FILE} in OpenSCAD")
    print(f"✓ Check {DEBUG_VIZ_FILE} to verify polygon and pyramid alignment")


if __name__ == "__main__":
    main()
