"""OpenSCAD source generation.

Phase 3.1 split this out of ``stomppad/__init__.py``:

- :func:`generate_openscad_with_positions` is the legacy single-shape
  generator (preserved byte-for-byte so the Phase 0 regression fixture
  keeps producing identical scad). Uses ``import(svg_file)`` + ``resize()``
  on the source SVG; only works when one body == the whole SVG.
- :func:`generate_body_scad` is the Phase 3 multi-body generator. Inlines
  each body's geometry as ``polygon(points=…)`` so it works on bodies
  that are arbitrary user-defined groupings (potentially a subset of the
  SVG, or merged across disjoint shapes).
- :func:`generate_per_body_scads` is the convenience wrapper the exporters
  call: takes a :class:`stomppad.project.ShapeProject` + a
  :class:`stomppad.cache.BodyOutputCache` and yields one SCAD per enabled
  body in a stable order.

The wasm-CGAL coplanar-face workaround (sink pyramids 0.01mm into the
base; build base + outline rim as one ``union(difference(…))``) is
preserved in both generators — Phase 0 documented the crash signature
and the manifold backend tolerates the workaround at zero cost.
"""
from __future__ import annotations

from typing import Optional

from .cache import DEFAULT_PACK_PARAMS, _merged_pack_params
from .project import Body, ShapeProject


# Defaults that the legacy single-shape pipeline ships with; the multi-body
# generator falls back to these when a project's global_params (or a body's
# pyramid_overrides) is silent on a key. Kept here rather than imported from
# `cache` for callers that want to render without instantiating a cache.
DEFAULT_RENDER_PARAMS = {
    "base_thickness": 2.5,
    "outline_offset": 2,
    "outline_height": 2,
    "pyramid_size": 4,
    "pyramid_height": 3.5,
    "pyramid_style": 4,
}


def _log(logger, message):
    (logger or print)(message)


# --------------------------------------------------------------------------- #
# Legacy single-shape generator — DO NOT modify without recapturing the Phase 0
# golden (tests/fixtures/sample_golden.scad).
# --------------------------------------------------------------------------- #


def generate_openscad_with_positions(
        svg_file,
        valid_positions,
        output_file,
        svg_info=None,
        logger=None,
        **params,
):
    """Single-shape SCAD generator. Imports the source SVG and applies one
    skeleton-packed pyramid layout. Preserved verbatim from Phase 0 so the
    regression fixture (tests/fixtures/sample_golden.scad) stays
    byte-identical.
    """

    has_rotation = len(valid_positions[0]) == 3 if valid_positions else False
    viewbox_height = svg_info['viewbox_height'] if svg_info else 0

    scad_code = f"""// AUTO-GENERATED by pyramid position calculator
// Valid pyramid positions pre-calculated from SVG boundary
//
// COORDINATE SYSTEM NOTES:
// - Python parses SVG with Y-axis DOWN (SVG native coordinates)
// - OpenSCAD imports SVG with Y-axis UP (standard 3D coordinates)
// - SVG coordinates are kept in viewBox space (not translated to origin)
// - Y coordinates are flipped: Y_openscad = viewbox_height - Y_python
// - X coordinates remain the same
//
// ROTATION NOTES:
// - Rotation angles calculated from skeleton tangent direction
// - Rotation is relative (tangent direction), so Y-flip doesn't affect it
// - Includes both path-following rotation AND 45° base diamond orientation
// - OpenSCAD applies the rotation directly (already includes diamond rotation)

// ===== PARAMETERS =====
svg_file = "{svg_file}";
// Final dimensions after scaling (calculated by Python)
final_width = {svg_info.get('final_width', params.get('target_width', 100)) if svg_info else params.get('target_width', 100)};
final_height = {svg_info.get('final_height', 0) if svg_info else 0};

base_thickness = {params.get('base_thickness', 2)};
outline_offset = {params.get('outline_offset', 2)};
outline_height = {params.get('outline_height', 0.8)};

pyramid_size = {params.get('pyramid_size', 4)};
pyramid_height = {params.get('pyramid_height', 2.5)};
pyramid_style = {params.get('pyramid_style', 4)};

total_height = base_thickness + outline_height;

// ===== PRE-CALCULATED VALID POSITIONS =====
// These positions have been verified to fit completely inside the SVG boundary
// Format: {"[x, y, rotation]" if has_rotation else "[x, y]"}
// Y-coordinates are flipped to match OpenSCAD's coordinate system
// rotation = angle in degrees for path-following orientation
valid_pyramid_positions = [
"""

    for pos in valid_positions:
        x = pos[0]
        y_flipped = viewbox_height - pos[1]
        if has_rotation:
            rotation = pos[2]
            scad_code += f"    [{x:.3f}, {y_flipped:.3f}, {rotation:.3f}],\n"
        else:
            scad_code += f"    [{x:.3f}, {y_flipped:.3f}],\n"

    scad_code += """];

// ===== MODULES =====

module scaled_svg() {
    // Note: OpenSCAD import() automatically handles SVG coordinate system
    // The imported SVG will match the OpenSCAD coordinate system
    // Use resize with both dimensions if height is specified, otherwise auto-scale
    resize([final_width, final_height > 0 ? final_height : 0, 0], auto=true) {
        import(svg_file);
    }
}

module base_shape_2d() {
    scaled_svg();
}

module outlined_shape_2d() {
    offset(r = outline_offset) {
        base_shape_2d();
    }
}

module grip_pyramid(path_rotation=0) {
    // Match the Python footprint calculation: 45° base + path_rotation
    // This ensures OpenSCAD pyramids match the debug visualization
    rotate([0, 0, 45 + path_rotation]) {
        cylinder(
            h = pyramid_height,
            r1 = pyramid_size / 1.414,
            r2 = 0,
            $fn = pyramid_style
        );
    }
}

// Place pyramids at pre-calculated positions
module pyramids_on_surface() {
    for (pos = valid_pyramid_positions) {
"""

    if has_rotation:
        scad_code += """        translate([pos[0], pos[1], base_thickness - 0.01]) {
            grip_pyramid(path_rotation=pos[2]);
        }
"""
    else:
        scad_code += """        translate([pos[0], pos[1], base_thickness - 0.01]) {
            grip_pyramid();
        }
"""

    scad_code += """    }
}

// ===== ASSEMBLY =====

module stomp_pad_complete() {
    // Base + raised rim as a single body. The earlier two-block formulation
    // (separate base extrude + outlined difference) had a redundant volume —
    // base_shape is a subset of outlined_shape, and the difference only cuts
    // above z=base_thickness, so the base block was fully contained in the
    // outline block. The shared face crashed openscad-wasm's CGAL kernel
    // (CGAL/Nef_3/SNC_external_structure.h:1144). Native OpenSCAD's manifold
    // backend tolerates it; the wasm build does not.
    union() {
        difference() {
            linear_extrude(height = total_height) {
                outlined_shape_2d();
            }
            translate([0, 0, base_thickness]) {
                linear_extrude(height = total_height) {
                    base_shape_2d();
                }
            }
        }

        pyramids_on_surface();
    }
}

stomp_pad_complete();
"""

    with open(output_file, 'w') as f:
        f.write(scad_code)

    _log(logger, f"Generated {output_file}")
    _log(logger, f"Valid pyramid positions: {len(valid_positions)}")


# --------------------------------------------------------------------------- #
# Phase 3.1 multi-body generator
# --------------------------------------------------------------------------- #


def _flip_y(coords, viewbox_height: float) -> str:
    """Format a ring as a SCAD ``points=[…]`` literal, Y-flipped to OpenSCAD's
    coordinate system (Y-up vs SVG's Y-down)."""
    return ", ".join(
        f"[{x:.3f}, {viewbox_height - y:.3f}]" for x, y in coords
    )


def _component_to_polygon_scad(component, viewbox_height: float, indent: str = "        ") -> str:
    """Render a :class:`Component` as a SCAD 2D shape (``polygon`` with
    ``difference()`` for holes). Self-contained — does not depend on the
    source SVG."""
    exterior = _flip_y(component.exterior, viewbox_height)
    if not component.holes:
        return f"{indent}polygon(points=[{exterior}]);"
    inner = "\n".join(
        f"{indent}    polygon(points=[{_flip_y(h, viewbox_height)}]);"
        for h in component.holes
    )
    return (
        f"{indent}difference() {{\n"
        f"{indent}    polygon(points=[{exterior}]);\n"
        f"{inner}\n"
        f"{indent}}}"
    )


def generate_body_scad(
    project: ShapeProject,
    body: Body,
    positions,
    *,
    params: Optional[dict] = None,
) -> str:
    """Self-contained SCAD that renders one body to a single STL.

    The body's geometry is **inlined** as ``polygon()`` calls rather than
    via ``import(svg_file) + resize()``, so the SCAD has no external file
    dependency and works on user-defined body groupings (which may merge
    disjoint shapes or include only a subset of the SVG's paths).

    ``positions`` are the packed pyramid positions for this body — usually
    obtained from :meth:`stomppad.cache.BodyOutputCache.positions_for`.
    ``params`` overlays the project's global_params on the default render
    params (``DEFAULT_RENDER_PARAMS``); per-body ``pyramid_overrides`` are
    expected to already be merged in by the caller.
    """
    if params is None:
        params = {}
    merged = {**DEFAULT_RENDER_PARAMS, **project.global_params, **params}
    base_thickness = merged["base_thickness"]
    outline_height = merged["outline_height"]
    pyramid_size = merged["pyramid_size"]
    pyramid_height = merged["pyramid_height"]
    pyramid_style = merged["pyramid_style"]

    viewbox_height = float(project.svg_info.get("viewbox_height") or 0)
    color = body.color_hex or "#cccccc"

    component_blocks = []
    for cid in body.component_ids:
        comp = project.component_or_none(cid)
        if comp is None:
            continue
        component_blocks.append(_component_to_polygon_scad(comp, viewbox_height))
    if not component_blocks:
        # Empty body — still emit a valid (zero-volume) SCAD so the caller
        # can decide whether to skip rendering.
        component_blocks.append("        // (no components)")

    has_rotation = bool(positions) and len(positions[0]) == 3
    position_lines = []
    for pos in positions:
        x = pos[0]
        y_flipped = viewbox_height - pos[1]
        if has_rotation:
            rot = pos[2]
            position_lines.append(f"    [{x:.3f}, {y_flipped:.3f}, {rot:.3f}],")
        else:
            position_lines.append(f"    [{x:.3f}, {y_flipped:.3f}],")
    positions_block = "\n".join(position_lines) if position_lines else "    // (no pyramids)"

    shape_block = "\n".join(component_blocks)
    pyramid_arg = (
        "grip_pyramid(path_rotation=pos[2])" if has_rotation else "grip_pyramid()"
    )

    return f"""// AUTO-GENERATED — body {body.id} ({body.name}), color={color}
// pattern={body.pattern}  •  components={body.component_ids}
// COORDINATE SYSTEM: SVG Y-down flipped to OpenSCAD Y-up via viewbox_height.

base_thickness = {base_thickness};
outline_height = {outline_height};
pyramid_size = {pyramid_size};
pyramid_height = {pyramid_height};
pyramid_style = {pyramid_style};
total_height = base_thickness + outline_height;

valid_pyramid_positions = [
{positions_block}
];

module body_shape_2d() {{
    union() {{
{shape_block}
    }}
}}

module grip_pyramid(path_rotation=0) {{
    // 45° diamond + path rotation; matches Python's pyramid footprint.
    rotate([0, 0, 45 + path_rotation]) {{
        cylinder(
            h = pyramid_height,
            r1 = pyramid_size / 1.414,
            r2 = 0,
            $fn = pyramid_style
        );
    }}
}}

module body_pyramids() {{
    for (pos = valid_pyramid_positions) {{
        // 0.01mm sink — same wasm-CGAL coplanar-face workaround documented
        // in the Phase 0 single-shape generator.
        translate([pos[0], pos[1], base_thickness - 0.01]) {{
            {pyramid_arg};
        }}
    }}
}}

module body_part() {{
    union() {{
        linear_extrude(height = total_height) body_shape_2d();
        body_pyramids();
    }}
}}

body_part();
"""


def generate_per_body_scads(project: ShapeProject, cache) -> dict[int, str]:
    """Return ``{body_id: scad_source}`` for every enabled body in the project.

    Skips disabled bodies. Empty bodies (no components) produce a SCAD that
    renders an empty solid — the caller can choose to skip the OpenSCAD
    invocation for those.
    """
    out: dict[int, str] = {}
    for body in project.bodies:
        if not body.enabled:
            continue
        positions = cache.positions_for(body.id)
        merged = _merged_pack_params(project, body)
        out[body.id] = generate_body_scad(
            project, body, positions, params=merged
        )
    return out
