// AUTO-GENERATED by pyramid position calculator
// Valid pyramid positions pre-calculated from SVG boundary
//
// COORDINATE SYSTEM NOTES:
// - Python parses SVG with Y-axis DOWN (SVG native coordinates)
// - OpenSCAD imports SVG with Y-axis UP (standard 3D coordinates)
// - SVG coordinates are kept in viewBox space (not translated to origin)
// - Y coordinates are flipped: Y_openscad = viewbox_height - Y_python
// - X coordinates remain the same
//
// ROTATION NOTES:
// - Rotation angles calculated from skeleton tangent direction
// - Rotation is relative (tangent direction), so Y-flip doesn't affect it
// - Includes both path-following rotation AND 45° base diamond orientation
// - OpenSCAD applies the rotation directly (already includes diamond rotation)

// ===== PARAMETERS =====
svg_file = "sample.svg";
// Final dimensions after scaling (calculated by Python)
final_width = 40.0;
final_height = 40.0;

base_thickness = 2;
outline_offset = 2;
outline_height = 0.8;

pyramid_size = 4;
pyramid_height = 2.5;
pyramid_style = 4;

total_height = base_thickness + outline_height;

// ===== PRE-CALCULATED VALID POSITIONS =====
// These positions have been verified to fit completely inside the SVG boundary
// Format: [x, y, rotation]
// Y-coordinates are flipped to match OpenSCAD's coordinate system
// rotation = angle in degrees for path-following orientation
valid_pyramid_positions = [
    [12.500, 40.670, 45.000],
    [17.500, 40.670, 0.000],
    [22.500, 40.670, 0.000],
    [27.500, 40.670, 0.000],
    [32.500, 40.670, 0.000],
    [37.500, 40.670, 135.000],
    [10.000, 36.340, 45.000],
    [15.000, 36.340, 45.000],
    [20.000, 36.340, 0.000],
    [25.000, 36.340, 0.000],
    [30.000, 36.340, 0.000],
    [35.000, 36.340, 135.000],
    [40.000, 36.340, 135.000],
    [7.500, 32.010, 0.000],
    [12.500, 32.010, 0.000],
    [17.500, 32.010, 45.000],
    [22.500, 32.010, 0.000],
    [27.500, 32.010, 0.000],
    [32.500, 32.010, 135.000],
    [37.500, 32.010, 0.000],
    [42.500, 32.010, 0.000],
    [10.000, 27.679, 0.000],
    [15.000, 27.679, 0.000],
    [20.000, 27.679, 45.000],
    [25.000, 27.679, 0.000],
    [30.000, 27.679, 135.000],
    [35.000, 27.679, 0.000],
    [40.000, 27.679, 0.000],
    [7.500, 23.349, 0.000],
    [12.500, 23.349, 0.000],
    [17.500, 23.349, 0.000],
    [22.500, 23.349, 132.203],
    [27.500, 23.349, 47.797],
    [32.500, 23.349, 0.000],
    [37.500, 23.349, 0.000],
    [42.500, 23.349, 0.000],
    [10.000, 19.019, 0.000],
    [15.000, 19.019, 135.000],
    [20.000, 19.019, 135.000],
    [25.000, 19.019, 0.000],
    [30.000, 19.019, 45.000],
    [35.000, 19.019, 45.000],
    [40.000, 19.019, 0.000],
    [7.500, 14.689, 0.000],
    [12.500, 14.689, 135.000],
    [17.500, 14.689, 135.000],
    [22.500, 14.689, 0.000],
    [27.500, 14.689, 0.000],
    [32.500, 14.689, 45.000],
    [37.500, 14.689, 45.000],
    [42.500, 14.689, 0.000],
    [10.000, 10.359, 135.000],
    [15.000, 10.359, 0.000],
    [20.000, 10.359, 0.000],
    [25.000, 10.359, 0.000],
    [30.000, 10.359, 0.000],
    [35.000, 10.359, 0.000],
    [40.000, 10.359, 45.000],
];

// ===== MODULES =====

module scaled_svg() {
    // Note: OpenSCAD import() automatically handles SVG coordinate system
    // The imported SVG will match the OpenSCAD coordinate system
    // Use resize with both dimensions if height is specified, otherwise auto-scale
    resize([final_width, final_height > 0 ? final_height : 0, 0], auto=true) {
        import(svg_file);
    }
}

module base_shape_2d() {
    scaled_svg();
}

module outlined_shape_2d() {
    offset(r = outline_offset) {
        base_shape_2d();
    }
}

module grip_pyramid(path_rotation=0) {
    // Match the Python footprint calculation: 45° base + path_rotation
    // This ensures OpenSCAD pyramids match the debug visualization
    rotate([0, 0, 45 + path_rotation]) {
        cylinder(
            h = pyramid_height,
            r1 = pyramid_size / 1.414,
            r2 = 0,
            $fn = pyramid_style
        );
    }
}

// Place pyramids at pre-calculated positions
module pyramids_on_surface() {
    for (pos = valid_pyramid_positions) {
        translate([pos[0], pos[1], base_thickness - 0.01]) {
            grip_pyramid(path_rotation=pos[2]);
        }
    }
}

// ===== ASSEMBLY =====

module stomp_pad_complete() {
    // Base + raised rim as a single body. The earlier two-block formulation
    // (separate base extrude + outlined difference) had a redundant volume —
    // base_shape is a subset of outlined_shape, and the difference only cuts
    // above z=base_thickness, so the base block was fully contained in the
    // outline block. The shared face crashed openscad-wasm's CGAL kernel
    // (CGAL/Nef_3/SNC_external_structure.h:1144). Native OpenSCAD's manifold
    // backend tolerates it; the wasm build does not.
    union() {
        difference() {
            linear_extrude(height = total_height) {
                outlined_shape_2d();
            }
            translate([0, 0, base_thickness]) {
                linear_extrude(height = total_height) {
                    base_shape_2d();
                }
            }
        }

        pyramids_on_surface();
    }
}

stomp_pad_complete();
